dist: trusty
sudo: false
language: rust

cache:
  - apt: true
  - cargo: true

branches:
  only:
    - master
    - /^\d+\.\d+\.x$/

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

  include:
    - rust: nightly-2018-09-11
      before_script:
        - rustup component add rustfmt-preview
        - export CARGO_INCREMENTAL=0
      script:
        - cargo update
        - cargo test
        - cargo fmt -- --check

    - rust: nightly
      env: LATEST_NIGHTLY
      before_script:
        - export CARGO_INCREMENTAL=0
      script:
        - cargo update
        - cargo test

    - rust: nightly-2018-09-11
      env: DEPLOY_API_DOC
      before_script:
      script:
        - rm -rf target/doc
        - cargo update
        - cargo doc
        - rm -f target/doc/.lock
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        repo: finchers-rs/finchers-juniper
        target_branch: gh-pages
        local_dir: target/doc
        on:
          branch: master
